### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by jwijffels** [suhitaghosh10/EurLexClassification#1]
hi, i see you've been using the udpipe package for annotation and I see you've been working on some text classification models also comparing different approaches.
I've recently put a package called [ruimtehol ](https://cran.r-project.org/web/packages/ruimtehol/)on CRAN (yesterday) which is good in multi-label classification and all kind of entity embeddings. As you look to be a person experimenting a lot with text analytic models, would you be willing to add to your classification model comparison that package. The cran package which I've put online has a vignette similar to the data setup you have - see https://cran.r-project.org/web/packages/ruimtehol/vignettes/ground-control-to-ruimtehol.pdf. I would be interested to see the resulting metrics in comparison to the existing methods you use

**Comment by suhitaghosh10** [comment]
Sure.. thank you for the suggestion
